allowBuilds:
  core-js-pure: true
  cypress: true
  esbuild: true
  sharp: false
  unrs-resolver: true
overrides:
  '@poncegl/material-design-3': file:../Material-Design-3-React/packages/material-design-3
