import type { Track } from './track';

export type PlaylistEntryStatus = 'ok' | 'orphaned';

export interface PlaylistEntry {
  trackId: Track['id'];
  filePath: string;
  title: string | null;
  artist: string | null;
  status: PlaylistEntryStatus;
}

export interface Playlist {
  id: string;
  name: string;
  filePath: string;
  entries: PlaylistEntry[];
  createdAt: string;
  autoGenerated: boolean;
}

export interface OrphanEntry extends Omit<PlaylistEntry, 'status'> {
  status: 'orphaned';
  lastKnownPath: string;
}
